# Вектор - одномерный массив

In [61]:
import numpy as np

In [62]:
# С векторами в NumPy можно производить арифметические операции: 
# складывать, вычитать, умножать друг на друга, 
# возводить один вектор в степень другого
# Операция, применённая к двум векторам, на самом деле применяется поэлементно.
# Вектора должны быть одинаковой длины.

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [63]:
# Сложение двух списков создает общий список значений.
list1 = [2, 4, 7, 2.5]
list2 = [12, 6, 3.6, 13]
list1 + list2


[2, 4, 7, 2.5, 12, 6, 3.6, 13]

In [64]:
# поэлементное сложение списков:
[x + y for x, y in zip(list1, list2)]

[14, 10, 10.6, 15.5]

In [65]:
# Операции можно применять к вектору и числу
vec = np.arange(5)
vec * 10 

array([ 0, 10, 20, 30, 40])

In [66]:
# Вектора можно сравнивать
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2

array([False, False,  True, False])

In [67]:
# Длина вектора, то есть расстояние между его началом и концом, 
# равна квадратный корень из суммы квадратов всех его координат. 
np.sqrt(np.sum(vec ** 2))

5.477225575051661

In [68]:
# функция из модуля линейной алгебры
np.linalg.norm(vec)

5.477225575051661

In [69]:
# расстояние между двуми векторами = длина из разности
np.sqrt(np.sum((vec1 - vec2) ** 2))
np.linalg.norm(vec1 - vec2)

15.026975743641833

In [70]:
# Скалярное произведение двух векторов есть сумма произведений их соответствующих координат.
np.sum(vec1 * vec2)
np.dot(vec1, vec2)

105.7

In [ ]:
# функции для статистики. min и max  два варианта
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()
np.max(vec)
vec.mean()