# Случайные числа

In [154]:
import numpy as np

In [155]:
# Случайное число от 0 до 1
np.random.rand()

0.6707490847267786

In [156]:
# Можно сразу массив, в том чисде многомерный 
# передаем аргумаентами а не кортеж
np.random.rand(2,5)

array([[0.82585276, 0.13670659, 0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749, 0.97862378, 0.81168315]])

In [157]:
# аналог с кортежем
shape = (2, 3)
np.random.sample(shape)

array([[0.17194101, 0.81622475, 0.27407375],
       [0.43170418, 0.94002982, 0.81764938]])

In [158]:
# функция uniform:
# uniform(low=0.0, high=1.0, size=None)
# Первые два аргумента — нижняя и верхняя границы диапазона в формате float, 
# третий опциональный  — форма массива (если не задан, возвращается одно число). 
# Форма массива задаётся кортежем или одним числом.
np.random.uniform(-1000, 500, size=(2, 3))

array([[-495.83207482, -736.88431939, -440.75193057],
       [-991.46723897, -621.36046983,  193.49376271]])

In [159]:
# функция random.randint:
# randint(low, high=None, size=None, dtype=int)
# Функцию randint нельзя запустить совсем без параметров, 
# необходимо указать хотя бы одно число.
#Если указан только аргумент low, числа будут генерироваться от 0 до low-1
#Если задать low и high, числа будут генерироваться от low (вкл-но) до high (не вкл-но).
# size задаёт форму массива: одним числом или кортежем .
# dtype позволяет задать конкретный тип данных.
np.random.randint(6, 12, size=(3,3))


array([[ 8, 11,  9],
       [ 6,  7,  6],
       [11, 10,  8]])

In [160]:
# Функция random.shuffle перемешивает тот массив, 
# к которому применяется, и возвращает None
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))
# None
arr

[0 1 2 3 4 5]
None


array([3, 4, 1, 2, 5, 0])

In [161]:
# Чтобы получить новый перемешанный массив, а исходный оставить без изменений, 
# можно использовать функцию random.permutation. 
# Она принимает на вход один аргумент — или массив целиком, или одно число:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

['ACDC' 'Deep Purple' 'The Beatles' 'Pink Floyd']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [162]:
# Перемешать набор чисел от 0 до n-1 
# можно с помощью записи np.random.permutation(n), где n — верхняя граница, 
# которая бы использовалась для генерации набора чисел функцией arange
np.random.permutation(10)

array([6, 8, 9, 7, 3, 0, 2, 4, 5, 1])

In [163]:
# Чтобы получить случайный набор объектов из массива, 
# используется функция random.choice: choice(a, size=None, replace=True)
# a — одномерный массив или число для генерации arange(a);
# size — желаемая форма массива 
# (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
# replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']
np.random.choice(workers, size=2, replace=False)


array(['Maria', 'Kate'], dtype='<U6')

In [164]:
# сгенерировать десять случайных чисел в диапазоне от 1 до 20 (включительно), 
# которые гарантированно не будут повторяться

np.random.choice(np.arange(1, 21), size=10, replace=False)

array([14,  2, 15, 13,  3,  6,  9, 12, 16,  1])

In [165]:
# Задать seed в NumPy можно с помощью функции np.random.seed(<np.uint32>). 
# Число в скобках должно быть в пределах от 0 до 2**32 - 1 (=4294967295).

np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]
